### ISSUE TITLE
run err: python test.py --arch FE-HAWP --dataset_name FE-Blurframe/FE-WHU --model_name FE-HAWP_FE-WHU.pkl --save_image 

### ISSUE THREAD

**Issue by Iwan2016** [lh9171338/FE-LSD#2]
I try to run :
it occured err:
python test.py --arch FE-HAWP --dataset_name FE-Blurframe/FE-WHU --model_name FE-HAWP_FE-WHU.pkl --save_image
gpu: 0
seed: 0
config_path: config
config_file: 
arch: FE-HAWP
dataset_path: dataset\FE-Blurframe/FE-WHU
dataset_name: FE-Blurframe/FE-WHU
image_size: (512, 512)
heatmap_size: (128, 128)
mean: [0.43031373, 0.40718431, 0.38698431]
std: [0.08735294, 0.08676078, 0.09109412]
log_path: log/FE-HAWP_FE-WHU
num_workers: 4
lr: 0.0004
weight_decay: 0.0001
step_size: 25
num_epochs: 30
last_epoch: -1
train_batch_size: 4
test_batch_size: 1
print_freq: 50
save_freq: 1
loss_weights: loss_dis: 1.0
loss_jloc: 8.0
loss_joff: 0.25
loss_md: 1.0
loss_neg: 1.0
loss_pos: 1.0
loss_res: 1.0
output_path: output\FE-Blurframe/FE-WHU-FE-HAWP_FE-WHU
figure_path: figure\FE-Blurframe/FE-WHU
save_image: True
with_clear: False
save_line: False
evaluate: False
score_thresh: 0.97
model_path: model
model_name: FE-HAWP_FE-WHU.pkl
pretrained_model_name:
depth: 4
num_stacks: 2
num_blocks: 1
inplanes: 64
num_feats: 256
head_size: [3, 1, 1, 2, 2]
dis_th: 5
ang_th: 0.1
n_stc_posl: 300
n_stc_negl: 40
n_dyn_junc: 300
junc_thresh: 0.008
n_dyn_posl: 300
n_dyn_negl: 300
n_pts0: 32
n_pts1: 8
dim_loi: 128
dim_fc: 1024
use_residual: True
use_gpu:  True
test:   0%|                                                                                                                                                   | 0/200 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 167, in <module>
    test(model, loader, cfg, device)
  File "test.py", line 83, in test
    for images, annotations in tqdm.tqdm(loader, desc='test: '):
  File "E:\anaconda3\envs\lsd3\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "E:\anaconda3\envs\lsd3\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\lsd3\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "E:\anaconda3\envs\lsd3\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\AI\FE-LSD\network\dataset.py", line 159, in __getitem__
    event = events['event'].astype(np.float32)
  File "E:\anaconda3\envs\lsd3\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'event is not a file in the archive'
 How to fix it? And I wanna only test a blur pic,what should I do?

**Comment by lh9171338** [comment]
You need to convert event streams into synchronous frames using Event Spike Tensor (EST) representation first. 
```shell
python event2frame.py --dataset_name <DATASET_NAME> --representation EST

# for FE-Wireframe dataset
python event2frame.py --dataset_name FE-Wireframe --representation EST

# for FE-Blurframe dataset
python event2frame.py --dataset_name FE-Blurframe --representation EST -s 0.5

ln -s events-EST-10 events
```

**Comment by Iwan2016** [comment]
Thanks,it works.
