### ISSUE TITLE
How to deblur a test pic?

### ISSUE THREAD

**Issue by Iwan2016** [lh9171338/FE-LSD#3]
How should I get my deblur pic with the pretrained model?
I try to run lilke this:
1、I build my test dir,includes:
    E:\FE-LSD\dataset\test
    E:\FE-LSD\dataset\test\images-blur
and add my test pic :
   E:\FE-LSD\dataset\test\images-blur\test1.png

2、run:
   python image2json.py --dataset_name test
and found it generated:
   E:\FE-LSD\dataset\test\test.json
the json content：
   [{"filename": "test1.png", "height": 572, "width": 552}]
Question:it didn't generate the file like: E:\FE-LSD\dataset\test\events\test1.npz?

3、run
python test.py --arch FE-ULSD --dataset_name test --model_name FE-ULSD_FE-WHU.pkl --save_image
   and occured err:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\test\\events\\test1.npz'

Consulting with modesty.

**Comment by lh9171338** [comment]
This code is about detecting line segments from two inputs, i.e. motion-blurred image and event data, rather than for image deblurring

**Comment by Iwan2016** [comment]
I get it,thanks a lot.
