### ISSUE TITLE
Test demo .so file

### ISSUE THREAD

**Issue by HongxiL** [lh9171338/FE-LSD#5]
Hello, when running the test demo code, I encountered an issue: _C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z13lsencode_cudaRKN2at6TensorEiiiii. Have you encountered this problem before, and can you provide a solution? Thank you.

**Comment by lh9171338** [comment]
Can you confirm whether the CUDA version matches the PyTorch version
